server:
  port: 8080
spring:
  application:
    name: library
  ### 数据源 ###
  datasource:
      druid:
        url: jdbc:mysql://127.0.0.1:3306/library?serverTimezone=GMT%2B8&characterEncoding=UTF-8
        username: root
        password:
        driver-class-name: com.mysql.cj.jdbc.Driver
        initial-size: 1
        max-active: 150
        min-idle: 1
        max-wait: 60000
        pool-prepared-statements: true
        max-pool-prepared-statement-per-connection-size: 20
        validation-query: SELECT 'x'
        test-on-borrow: false
        test-on-return: false
        test-while-idle: true
        time-between-eviction-runs-millis: 60000
  ###文件上传大小配置###
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    static-locations: E:\\images\\

###security 不需要拦截的路径###
secure:
  urls:
    exclude:
      - /swagger-ui.html
      - /swagger-resources/**
      - /swagger/**
      - /**/v2/api-docs
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.ico
      - /webjars/springfox-swagger-ui/**
      - /druid/**
      - /actuator/**
      - /user/login
      - /user/register

### JWT ###
jwt:
  config:
    key: secret
    ttl: 36000000

### mybatis-plus ###
mybatis-plus:
  mapper-locations: classpath*:mapper/xml/*.xml
###日志打印###
logging:
  level:
    com.library: debug

# 放开Actuator Web REST 端点
management:
  endpoints:
    web:
      base-path: /actuator  # 访问根路径
      exposure:
        include: "*"
    enabled-by-default: true
